# Form implementation generated from reading ui file 'Btn_InfoSettings.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_infosett_dialog(object):
    def setupUi(self, infosett_dialog):
        infosett_dialog.setObjectName("infosett_dialog")
        infosett_dialog.resize(500, 400)
        infosett_dialog.setStyleSheet("background-color: rgb(25, 35, 45);\n"
"color: rgb(255, 255, 255);\n"
"border-color: rgb(200, 200, 200);\n"
"\n"
"\n"
"")
        self.gridLayout_3 = QtWidgets.QGridLayout(infosett_dialog)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.infosett_dialog_tab = QtWidgets.QTabWidget(parent=infosett_dialog)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(25, 35, 45))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(25, 35, 45))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(25, 35, 45))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(25, 35, 45))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(25, 35, 45))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(25, 35, 45))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(25, 35, 45))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(25, 35, 45))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(25, 35, 45))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.PlaceholderText, brush)
        self.infosett_dialog_tab.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.infosett_dialog_tab.setFont(font)
        self.infosett_dialog_tab.setStyleSheet("QTabBar {\n"
"border-color: rgb(200, 200, 200);\n"
"}\n"
"\n"
"QTabBar::tab:selected, QTabBar::tab:hover {\n"
"background-color: rgb(45, 55, 65);\n"
"}")
        self.infosett_dialog_tab.setTabShape(QtWidgets.QTabWidget.TabShape.Triangular)
        self.infosett_dialog_tab.setElideMode(QtCore.Qt.TextElideMode.ElideLeft)
        self.infosett_dialog_tab.setMovable(True)
        self.infosett_dialog_tab.setObjectName("infosett_dialog_tab")
        self.tab_info = QtWidgets.QWidget()
        self.tab_info.setObjectName("tab_info")
        self.gridLayout = QtWidgets.QGridLayout(self.tab_info)
        self.gridLayout.setObjectName("gridLayout")
        self.info_funclabel = QtWidgets.QLabel(parent=self.tab_info)
        self.info_funclabel.setObjectName("info_funclabel")
        self.gridLayout.addWidget(self.info_funclabel, 0, 0, 1, 1)
        self.info_text = QtWidgets.QTextEdit(parent=self.tab_info)
        self.info_text.setObjectName("info_text")
        self.gridLayout.addWidget(self.info_text, 1, 0, 1, 1)
        self.infosett_dialog_tab.addTab(self.tab_info, "")
        self.tab_settings = QtWidgets.QWidget()
        self.tab_settings.setObjectName("tab_settings")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab_settings)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.settings_funclabel = QtWidgets.QLabel(parent=self.tab_settings)
        self.settings_funclabel.setObjectName("settings_funclabel")
        self.gridLayout_2.addWidget(self.settings_funclabel, 0, 0, 1, 1)
        self.settings_table = QtWidgets.QTableWidget(parent=self.tab_settings)
        self.settings_table.setStyleSheet("QHeaderView::section {\n"
"        background-color: rgb(45, 55, 65);\n"
"}")
        self.settings_table.setObjectName("settings_table")
        self.settings_table.setColumnCount(0)
        self.settings_table.setRowCount(0)
        self.gridLayout_2.addWidget(self.settings_table, 1, 0, 1, 1)
        self.infosett_dialog_tab.addTab(self.tab_settings, "")
        self.gridLayout_3.addWidget(self.infosett_dialog_tab, 0, 0, 1, 1)

        self.retranslateUi(infosett_dialog)
        self.infosett_dialog_tab.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(infosett_dialog)

    def retranslateUi(self, infosett_dialog):
        _translate = QtCore.QCoreApplication.translate
        infosett_dialog.setWindowTitle(_translate("infosett_dialog", "Dialog"))
        self.info_funclabel.setText(_translate("infosett_dialog", "TextLabel"))
        self.infosett_dialog_tab.setTabText(self.infosett_dialog_tab.indexOf(self.tab_info), _translate("infosett_dialog", "Info"))
        self.settings_funclabel.setText(_translate("infosett_dialog", "TextLabel"))
        self.infosett_dialog_tab.setTabText(self.infosett_dialog_tab.indexOf(self.tab_settings), _translate("infosett_dialog", "Settings"))
