# Form implementation generated from reading ui file 'FunctionViewer.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_functionviewer_dialog(object):
    def setupUi(self, functionviewer_dialog):
        functionviewer_dialog.setObjectName("functionviewer_dialog")
        functionviewer_dialog.resize(1000, 840)
        functionviewer_dialog.setStyleSheet("background-color: rgb(25, 35, 45);\n"
"color: rgb(255, 255, 255);\n"
"border-color: rgb(200, 200, 200);\n"
"\n"
"")
        self.gridLayout_2 = QtWidgets.QGridLayout(functionviewer_dialog)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.functionviewer_dialog_btnbox = QtWidgets.QDialogButtonBox(parent=functionviewer_dialog)
        self.functionviewer_dialog_btnbox.setLocale(QtCore.QLocale(QtCore.QLocale.Language.English, QtCore.QLocale.Country.Europe))
        self.functionviewer_dialog_btnbox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.functionviewer_dialog_btnbox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Apply|QtWidgets.QDialogButtonBox.StandardButton.Cancel)
        self.functionviewer_dialog_btnbox.setCenterButtons(False)
        self.functionviewer_dialog_btnbox.setObjectName("functionviewer_dialog_btnbox")
        self.gridLayout_2.addWidget(self.functionviewer_dialog_btnbox, 6, 2, 1, 4)
        self.functionviewer_functree = QtWidgets.QTreeWidget(parent=functionviewer_dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.functionviewer_functree.sizePolicy().hasHeightForWidth())
        self.functionviewer_functree.setSizePolicy(sizePolicy)
        self.functionviewer_functree.setStyleSheet("QHeaderView::section {\n"
"        background-color: rgb(45, 55, 65);\n"
"}")
        self.functionviewer_functree.setIndentation(20)
        self.functionviewer_functree.setObjectName("functionviewer_functree")
        self.functionviewer_functree.headerItem().setText(0, "1")
        self.functionviewer_functree.header().setVisible(False)
        self.gridLayout_2.addWidget(self.functionviewer_functree, 1, 0, 6, 2)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 3, 5, 1, 1)
        self.functionviewer_funcname = QtWidgets.QLabel(parent=functionviewer_dialog)
        self.functionviewer_funcname.setObjectName("functionviewer_funcname")
        self.gridLayout_2.addWidget(self.functionviewer_funcname, 0, 0, 1, 2)
        self.functionviewer_data_ManEval = QtWidgets.QLabel(parent=functionviewer_dialog)
        self.functionviewer_data_ManEval.setObjectName("functionviewer_data_ManEval")
        self.gridLayout_2.addWidget(self.functionviewer_data_ManEval, 3, 2, 1, 1)
        self.functionviewer_ManEval = QtWidgets.QComboBox(parent=functionviewer_dialog)
        self.functionviewer_ManEval.setObjectName("functionviewer_ManEval")
        self.functionviewer_ManEval.addItem("")
        self.functionviewer_ManEval.addItem("")
        self.gridLayout_2.addWidget(self.functionviewer_ManEval, 3, 3, 1, 1)
        self.functionviewer_label_up = QtWidgets.QLabel(parent=functionviewer_dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.functionviewer_label_up.sizePolicy().hasHeightForWidth())
        self.functionviewer_label_up.setSizePolicy(sizePolicy)
        self.functionviewer_label_up.setObjectName("functionviewer_label_up")
        self.gridLayout_2.addWidget(self.functionviewer_label_up, 0, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 0, 3, 1, 3)
        self.functionviewer_docstring = QtWidgets.QTextEdit(parent=functionviewer_dialog)
        self.functionviewer_docstring.setObjectName("functionviewer_docstring")
        self.gridLayout_2.addWidget(self.functionviewer_docstring, 5, 2, 1, 4)
        self.functionviewer_attr_assignment = QtWidgets.QTableWidget(parent=functionviewer_dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.functionviewer_attr_assignment.sizePolicy().hasHeightForWidth())
        self.functionviewer_attr_assignment.setSizePolicy(sizePolicy)
        self.functionviewer_attr_assignment.setStyleSheet("QHeaderView::section {\n"
"        background-color: rgb(45, 55, 65);\n"
"}")
        self.functionviewer_attr_assignment.setObjectName("functionviewer_attr_assignment")
        self.functionviewer_attr_assignment.setColumnCount(0)
        self.functionviewer_attr_assignment.setRowCount(0)
        self.gridLayout_2.addWidget(self.functionviewer_attr_assignment, 4, 2, 1, 4)

        self.retranslateUi(functionviewer_dialog)
        self.functionviewer_dialog_btnbox.accepted.connect(functionviewer_dialog.accept) # type: ignore
        self.functionviewer_dialog_btnbox.rejected.connect(functionviewer_dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(functionviewer_dialog)

    def retranslateUi(self, functionviewer_dialog):
        _translate = QtCore.QCoreApplication.translate
        functionviewer_dialog.setWindowTitle(_translate("functionviewer_dialog", "Dialog"))
        self.functionviewer_funcname.setText(_translate("functionviewer_dialog", "Function name:"))
        self.functionviewer_data_ManEval.setText(_translate("functionviewer_dialog", "Data Manipulation or Evaluation"))
        self.functionviewer_ManEval.setItemText(0, _translate("functionviewer_dialog", "Manipulation"))
        self.functionviewer_ManEval.setItemText(1, _translate("functionviewer_dialog", "Evaluation"))
        self.functionviewer_label_up.setText(_translate("functionviewer_dialog", "Assignment and Description:"))
