# Form implementation generated from reading ui file 'HDF5Preview.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_hdf5preview_dialog(object):
    def setupUi(self, hdf5preview_dialog):
        hdf5preview_dialog.setObjectName("hdf5preview_dialog")
        hdf5preview_dialog.resize(1000, 840)
        hdf5preview_dialog.setStyleSheet("background-color: rgb(25, 35, 45);\n"
"color: rgb(255, 255, 255);\n"
"border-color: rgb(200, 200, 200);\n"
"\n"
"")
        self.gridLayout_2 = QtWidgets.QGridLayout(hdf5preview_dialog)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 0, 4, 1, 1)
        self.hdf5preview_filename = QtWidgets.QLabel(parent=hdf5preview_dialog)
        self.hdf5preview_filename.setObjectName("hdf5preview_filename")
        self.gridLayout_2.addWidget(self.hdf5preview_filename, 0, 0, 1, 2)
        self.hdf5preview_dialog_btnbox = QtWidgets.QDialogButtonBox(parent=hdf5preview_dialog)
        self.hdf5preview_dialog_btnbox.setLocale(QtCore.QLocale(QtCore.QLocale.Language.English, QtCore.QLocale.Country.Europe))
        self.hdf5preview_dialog_btnbox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.hdf5preview_dialog_btnbox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Apply|QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Open)
        self.hdf5preview_dialog_btnbox.setObjectName("hdf5preview_dialog_btnbox")
        self.gridLayout_2.addWidget(self.hdf5preview_dialog_btnbox, 4, 2, 1, 3)
        self.hdf5preview_table_data = QtWidgets.QTableWidget(parent=hdf5preview_dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(8)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.hdf5preview_table_data.sizePolicy().hasHeightForWidth())
        self.hdf5preview_table_data.setSizePolicy(sizePolicy)
        self.hdf5preview_table_data.setStyleSheet("QHeaderView::section {\n"
"        background-color: rgb(45, 55, 65);\n"
"}")
        self.hdf5preview_table_data.setObjectName("hdf5preview_table_data")
        self.hdf5preview_table_data.setColumnCount(0)
        self.hdf5preview_table_data.setRowCount(0)
        self.gridLayout_2.addWidget(self.hdf5preview_table_data, 2, 3, 1, 2)
        self.hdf5preview_filepath = QtWidgets.QLabel(parent=hdf5preview_dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.hdf5preview_filepath.sizePolicy().hasHeightForWidth())
        self.hdf5preview_filepath.setSizePolicy(sizePolicy)
        self.hdf5preview_filepath.setObjectName("hdf5preview_filepath")
        self.gridLayout_2.addWidget(self.hdf5preview_filepath, 0, 3, 1, 1)
        self.hdf5preview_tree = QtWidgets.QTreeWidget(parent=hdf5preview_dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.hdf5preview_tree.sizePolicy().hasHeightForWidth())
        self.hdf5preview_tree.setSizePolicy(sizePolicy)
        self.hdf5preview_tree.setStyleSheet("QHeaderView::section {\n"
"        background-color: rgb(45, 55, 65);\n"
"}")
        self.hdf5preview_tree.setIndentation(20)
        self.hdf5preview_tree.setObjectName("hdf5preview_tree")
        self.hdf5preview_tree.headerItem().setText(0, "1")
        self.hdf5preview_tree.header().setVisible(False)
        self.gridLayout_2.addWidget(self.hdf5preview_tree, 1, 0, 4, 2)
        self.hdf5preview_table_attr = QtWidgets.QTableWidget(parent=hdf5preview_dialog)
        self.hdf5preview_table_attr.setStyleSheet("QHeaderView::section {\n"
"        background-color: rgb(45, 55, 65);\n"
"}")
        self.hdf5preview_table_attr.setObjectName("hdf5preview_table_attr")
        self.hdf5preview_table_attr.setColumnCount(0)
        self.hdf5preview_table_attr.setRowCount(0)
        self.gridLayout_2.addWidget(self.hdf5preview_table_attr, 1, 3, 1, 2)

        self.retranslateUi(hdf5preview_dialog)
        self.hdf5preview_dialog_btnbox.accepted.connect(hdf5preview_dialog.accept) # type: ignore
        self.hdf5preview_dialog_btnbox.rejected.connect(hdf5preview_dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(hdf5preview_dialog)

    def retranslateUi(self, hdf5preview_dialog):
        _translate = QtCore.QCoreApplication.translate
        hdf5preview_dialog.setWindowTitle(_translate("hdf5preview_dialog", "Dialog"))
        self.hdf5preview_filename.setText(_translate("hdf5preview_dialog", "Filename:"))
        self.hdf5preview_filepath.setText(_translate("hdf5preview_dialog", "Filepath:"))
